// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PermissionManagement.API.Infrastructure.Data;

#nullable disable

namespace PermissionManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505000020_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionManagement.API.Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PermissionManagement.API.Domain.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");
                });

            modelBuilder.Entity("PermissionManagement.API.Domain.Entities.PermissionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTemplates");
                });

            modelBuilder.Entity("PermissionManagement.API.Domain.Entities.Admin", b =>
                {
                    b.OwnsMany("PermissionManagement.API.Domain.Entities.ActionPermissionEntry", "ActionPermissions", b1 =>
                        {
                            b1.Property<int>("AdminId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int[]>("Actions")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<List<int>>("AllowedGovernorates")
                                .HasColumnType("integer[]");

                            b1.Property<List<string>>("AllowedTargets")
                                .HasColumnType("text[]");

                            b1.Property<int>("ServiceType")
                                .HasColumnType("integer");

                            b1.HasKey("AdminId", "Id");

                            b1.ToTable("Admins");

                            b1.ToJson("ActionPermissions");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.OwnsMany("PermissionManagement.API.Domain.Entities.ViewPermissionEntry", "ViewPermissions", b1 =>
                        {
                            b1.Property<int>("AdminId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<List<int>>("AllowedGovernorates")
                                .HasColumnType("integer[]");

                            b1.Property<List<int>>("AllowedStatuses")
                                .HasColumnType("integer[]");

                            b1.Property<List<string>>("AllowedTargets")
                                .HasColumnType("text[]");

                            b1.Property<int>("ServiceType")
                                .HasColumnType("integer");

                            b1.HasKey("AdminId", "Id");

                            b1.ToTable("Admins");

                            b1.ToJson("ViewPermissions");

                            b1.WithOwner()
                                .HasForeignKey("AdminId");
                        });

                    b.Navigation("ActionPermissions");

                    b.Navigation("ViewPermissions");
                });

            modelBuilder.Entity("PermissionManagement.API.Domain.Entities.PermissionTemplate", b =>
                {
                    b.OwnsMany("PermissionManagement.API.Domain.Entities.ActionPermissionEntry", "ActionPermissions", b1 =>
                        {
                            b1.Property<int>("PermissionTemplateId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int[]>("Actions")
                                .IsRequired()
                                .HasColumnType("integer[]");

                            b1.Property<List<int>>("AllowedGovernorates")
                                .HasColumnType("integer[]");

                            b1.Property<List<string>>("AllowedTargets")
                                .HasColumnType("text[]");

                            b1.Property<int>("ServiceType")
                                .HasColumnType("integer");

                            b1.HasKey("PermissionTemplateId", "Id");

                            b1.ToTable("PermissionTemplates");

                            b1.ToJson("ActionPermissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionTemplateId");
                        });

                    b.OwnsMany("PermissionManagement.API.Domain.Entities.ViewPermissionEntry", "ViewPermissions", b1 =>
                        {
                            b1.Property<int>("PermissionTemplateId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<List<int>>("AllowedGovernorates")
                                .HasColumnType("integer[]");

                            b1.Property<List<int>>("AllowedStatuses")
                                .HasColumnType("integer[]");

                            b1.Property<List<string>>("AllowedTargets")
                                .HasColumnType("text[]");

                            b1.Property<int>("ServiceType")
                                .HasColumnType("integer");

                            b1.HasKey("PermissionTemplateId", "Id");

                            b1.ToTable("PermissionTemplates");

                            b1.ToJson("ViewPermissions");

                            b1.WithOwner()
                                .HasForeignKey("PermissionTemplateId");
                        });

                    b.Navigation("ActionPermissions");

                    b.Navigation("ViewPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
